CREATE TABLE eg_user (
    id serial not null primary key,
    title character varying(8),
    salutation character varying(5),
    dob timestamp,
    locale character varying(16),
    username character varying(64) NOT NULL,
    password character varying(64) NOT NULL,
    pwd_expiry_date timestamp DEFAULT CURRENT_TIMESTAMP,
    mobile_number character varying(50),
    alt_contact_number character varying(50),
    email_id character varying(128),
    created_date timestamp,
    last_modified_date timestamp,
    created_by bigint,
    last_modified_by bigint,
    active boolean,
    name character varying(100),
    gender smallint,
    pan character varying(10),
    aadhaar_number character varying(20),
    type character varying(50),
    version numeric DEFAULT 0,
    guardian character varying(100),
    guardian_relation character varying(32),
    signature bytea,
    account_locked boolean DEFAULT false,
    CONSTRAINT eg_user_user_name_key UNIQUE (username)
);